FROM jenkins/jenkins:lts
MAINTAINER Steve de Silva <steve.desilva@gmail.com>

# Suppress apt installation warnings
ENV DEBIAN_FRONTEND=noninteractive

# Change to root user
USER root


RUN apt-get update -y

RUN apt-get install -y --no-install-recommends \
    apt-transport-https \
    curl \
    software-properties-common 



RUN curl -fsSL 'https://sks-keyservers.net/pks/lookup?op=get&search=0xee6d536cf7dc86e2d7d56f59a178ac6c6238f52e' | apt-key add -


RUN add-apt-repository \
   "deb https://packages.docker.com/1.13/apt/repo/ \
   ubuntu-trusty \
   main"

RUN echo 'deb http://cz.archive.ubuntu.com/  trusty main' >> /etc/apt/sources.list.d/docker.list
# RUN echo 'deb https://packages.docker.com/1.13/apt/repo/ ubuntu-trusty main' >> /etc/apt/sources.list.d/docker.list

RUN apt-get update


RUN apt-get -y --allow-unauthenticated install docker-engine

# Change to jenkins user
USER jenkins

# Add Jenkins plugins
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt


